export const SETDONATIONS ='donations/setDonations'
export const SETTOKEN = 'access_token/setToken'
export const SETPAYLOADCREATE = 'donations/create'
export const SET_USER_DONATIONS = 'userDonations/setUserDonations'
export const SET_DETAIL_DONATION = 'detailDonation/setDetailDonation'
export const SET_USER_PROFILE = 'users/profile'
